[theme]
# primaryColor="#d0291b"
# backgroundColor="#212529"
# secondaryBackgroundColor="#2a2a2a"
# textColor="#ffffff"

# primaryColor="#A78295"
# backgroundColor="#331D2C"
# secondaryBackgroundColor="#3F2E3E"
# textColor="#EFE1D1"

# primaryColor="#393646"
# backgroundColor="#4F4557"
# secondaryBackgroundColor="#6D5D6E"
# textColor="#F4EEE0"

# everblush
primaryColor="#c47fd5"
backgroundColor="#141b1e"
secondaryBackgroundColor="#232a2d"
textColor="#dadada"
